;/* Version 396a4a3598e4fdd54b8073a93c951462 v:4.5.15.2703, c:daad973a3795ea57d617039886798b37a3d6620f, b:4.5.15.2703 */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
new function(){var k=window.ADRUM;if(k&&k.q&&!0!==window["adrum-disable"]){var B=window.console,y=B&&"function"==typeof B.log?B:{log:function(){}},v=this&&this.Ac||function(){var d=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,a){d.__proto__=a}||function(d,a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])};return function(h,a){function b(){this.constructor=h}d(h,a);h.prototype=null===a?Object.create(a):(b.prototype=a.prototype,new b)}}();(function(d){(function(h){h.Ja=function(a){function b(d){return d.replace(/\s/g,
"")===e}var l={a:[1,2,3,"str"]},e='{"a":[1,2,3,"str"]}';if("undefined"!==typeof JSON&&JSON&&h.isFunction(JSON.stringify)&&b(JSON.stringify(l)))return JSON.stringify(a);if("undefined"!==typeof Object&&Object&&h.isFunction(Object.toJSON)&&b(Object.toJSON(l)))return Object.toJSON(a);d.log("M251");return null};h.Nc=function(a,b,l){var e=a,c=l;"xhr"===l&&(e=document.createElement("div"),a.appendChild(e),c="xhr_"+a.getElementsByTagName("div").length);a=document.createElement("p");a.innerHTML="Script loaded from "+
d.conf.adrumExtUrl+". Metrics collected are:";e.appendChild(a);a=document.createElement("table");a.id="ADRUM_"+c;var c=document.createElement("tbody"),g;for(g in b){l=document.createElement("tr");var h=document.createElement("td");h.innerHTML=g;h.className="name";var n=document.createElement("td");n.innerHTML=String(b[g]);n.className="value";l.appendChild(h);l.appendChild(n);c.appendChild(l)}a.appendChild(c);e.appendChild(a)};h.dumpObject=function(){function d(b,l){try{if("object"!=typeof b)return String(b);
if(0<=h.Lb(l,b))return"Already visited";l.push(b);var e;if(h.isArray(b)){for(var c="[ ",g=0;g<b.length;g++)0!=g&&(c+=", "),c+=d(b[g],l);e=c+" ]"}else{var c="{ ",g=!0,f;for(f in b)g?g=!1:c+=", ",c+=d(f,l)+" => "+d(b[f],l);e=c+" }"}return e}catch(n){return"dumpObject failed: "+n}}return function(b){return d(b,[])}}();h.Lb=h.isFunction(Array.prototype.indexOf)?function(d,b){return d.indexOf(b)}:function(d,b){for(var l=0;l<d.length;l++)if(d[l]==b)return l;return-1};h.compareWindows=function(d,b){return d==
b};h.Zc=function(d,b,l,e,c){if(!h.isDefined(b))return b;if(h.isArray(b)){d=[];for(var g=0,f=b.length;g<f;g++)d[g]=h.Zc(g,b[g],l,e,c);return d}if(h.isFunction(b))return b;if(h.isObject(b)){d={};for(g in b)h.hasOwnPropertyDefined(b,g)&&(d[l(g)]=c&&c(g)?b[g]:h.Zc(g,b[g],l,e,c));return d}return e(d,b)};h.sl=function(d){var b=[],l;for(l in d)h.hasOwnPropertyDefined(d,l)&&b.push([l,d[l]]);return b};h.Cm=function(){try{localStorage.setItem("try","try");var d=localStorage.getItem("try");localStorage.removeItem("try");
return"try"===d}catch(b){return!1}};h.Bm=function(){try{var d=h.Ja({v:1});return 1===JSON.parse(d).v}catch(b){return!1}};h.Dm=function(){return h.isFunction(window.postMessage)};h.rj=function(d,b){var l=document.createElement("div");l.innerHTML='<iframe id="'+b+'" src='+d+' width="0" height="0" tabindex="-1" title="empty" style="display: none;"></iframe>';document.body.appendChild(l);return document.getElementById(b)};h.Lg=function(d,b){h.isDefined(b)&&(d.parentPageName=b)};h.gd=function(d){return h.isNumber(d)&&
isFinite(d)&&Math.floor(d)===d};h.Ve=function(h){d.log(h);y.log(h)}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(d){d.Wg=function(d){return/^[0-9]+$/.test(d)?Number(d):null};d.Lf=function(d){return"number"===typeof d&&!isNaN(d)&&isFinite(d)}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(h){function a(c){var e=c.split("\r\n"),l=/^\s*ADRUM_(\d+): (.+)\s*$/i;c=[];for(var b=0;b<e.length;b++){var h=e[b];try{var a=l.exec(h);a&&c.push([Number(a[1]),a[2]])}catch(k){d.exception(k,
"M254",h)}}Array.prototype.sort.call(c,function(d,c){return d[0]-c[0]});a=[];for(e=0;e<c.length;e++)a.push(c[e][1]);return a}var b=d.utils.hasOwnPropertyDefined,l=null,e=null;h.yf=function(){e||(e=h.eg(h.ud(h.cookieMetadataChunks),h.ud(d.footerMetadataChunks)));return e};h.getPageGUID=function(){var c=d.monitor.DOMEventsMonitor,e=d.utils.isObject(c.currentBasePage)&&d.utils.isFunction(c.currentBasePage.guid);if(!l){var b=h.yf();l=b&&b.clientRequestGUID||(e?c.currentBasePage.guid():d.utils.generateGUID())}return l};
h.pk=function(c){c=a(c);d.log("M252",c);return h.eg(h.ud(c))};h.eg=function(c,e){function l(c){for(var e=0;e<c.length;e++){var g=c[e];g!=b&&0>d.utils.Lb(r,g)&&r.push(g)}}if(!c||0>=c.La.length)return null;e||(e=c);var b;if(0<e.La.length){if(b=e.La[0],0>d.utils.Lb(c.La,b))return null}else return d.error("M253"),null;var a=e.serverSnapshotType||c.serverSnapshotType,k=e.hasEntryPointErrors||c.hasEntryPointErrors,r=[];l(c.La);l(e.La);var q={clientRequestGUID:b,btGlobalAccountName:c.btGlobalAccountName};
0<r.length&&(q.otherClientRequestGUIDs=r);0<h.dg(c.btTime,e.btTime).length&&(q.btTime=h.dg(c.btTime,e.btTime));null!==a&&(q.serverSnapshotType=a);null!==k&&(q.hasEntryPointErrors=k);return q};h.dg=function(d,e){for(var l=d.concat(e),h={},a={},k=0;k<l.length;k++){var r=l[k];r.id in h||(h[r.id]=-1);h[r.id]=Math.max(h[r.id],r.duration);r.id in a||(a[r.id]=-1);a[r.id]=Math.max(a[r.id],r.ert)}var l=[],q;for(q in h)b(h,q)&&l.push({id:q,duration:h[q],ert:a[q]});return l};h.ud=function(c){if(!d.utils.isArray(c))return null;
for(var e=[],l=null,b=[],h=null,a=null,k=0;k<c.length;k++){var q=c[k];if("string"!==typeof q)return null;q=q.replace(/^"|"$/g,"");q=decodeURIComponent(q).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===q.length){var t=q[1];switch(q[0]){case "clientRequestGUID":case "g":e.push(t);break;case "btId":case "i":b.push({id:t,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;q=d.utils.Wg(t);if(!d.utils.Lf(q)||-1>q)return null;b[b.length-1].duration=q;break;case "btERT":case "e":if(0===
b.length)return null;q=d.utils.Wg(t);if(!d.utils.Lf(q)||-1>q)return null;b[b.length-1].ert=q;break;case "serverSnapshotType":case "s":h=t;break;case "globalAccountName":case "n":l=t;break;case "hasEntryPointErrors":case "h":a=t}}}return 0===e.length?null:{La:e,btGlobalAccountName:l,btTime:b,serverSnapshotType:h,hasEntryPointErrors:a}};h.fo=a})(d.correlation||(d.correlation={}))})(k||(k={}));(function(d){var h=d.conf||(d.conf={});h.mn=3E3;h.useDebugBeaconParams=d.isDebug;h.Ji=1E3;h.gi=2;h.fi=5;h.$h=
5;h.ai=20;h.oe=5E3;h.Za=512;h.Fh=10;h.Eh=64;h.ri=10;h.qi=10;h.mi=300;h.ji=2048;h.$a=2048;h.ab=760;h.Xf={eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",pageName:"pn",httpHeaders:"hh",parameter:"pa",navOrXhrMetrics:"mn",cookieMetrics:"mc",resourceTimingInfo:"rt",userData:"ud",userDataLong:"udl",userDataDouble:"udd",
userDataBoolean:"udb",userDataDate:"udt",errors:"er",ajaxError:"ae",xhrStatus:"xs",btTime:"bt",btGlobalAccountName:"btgan",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",eom:"em",agentId:"ai",rootGUID:"rg",events:"es",guids:"gs",urlParts:"up",sequenceId:"si",eventType:"et",eventGUID:"eg",parentType:"at",serverMetadata:"sm",eventUrl:"eu",line:"ln",message:"dm",duration:"dn",id:"id",ert:"ert",parentUrl:"au",
parentPageName:"an",geo:"ge",metrics:"mx",timestamp:"ts",country:"c",region:"r",city:"t",method:"md",clientId:"ci"}})(k||(k={}));(function(d){d=d.beacons||(d.beacons={});d.numBeaconsSent=0;d.beaconsSent=[]})(k||(k={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.send=function(l,e){var c=(e?d.conf.beaconUrlHttps:d.conf.beaconUrlHttp)+d.conf.corsEndpointPath+"/"+d.conf.appKey+"/adrum",b;d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrOpen)?(b=new d.xhrConstructor,
d.xhrOpen.call(b,"POST",c)):(b=new XMLHttpRequest,b.open("POST",c));b.setRequestHeader("Content-type","text/plain");var a=d.utils.Ja(l);null!=a&&(d.utils.isFunction(d.xhrConstructor)&&d.utils.isFunction(d.xhrSend)?d.xhrSend.call(b,a):b.send(a),d.log("M255",c),d.log("\n"),d.log("<hr/>"),d.isDebug&&h.beaconsSent.push(l),h.numBeaconsSent+=1)};return b}();h.zh=a})(d.beacons||(d.beacons={}))})(k||(k={}));k||(k={});(function(d){var h=function(){function h(d,l,e){this.Tb=d;this.Gk=l;this.Nd=e}h.prototype.Xc=
function(){try{return h.sf(this.Gk.ADRUM)}catch(b){return d.error("M256"),h.sf(d)}};h.sf=function(d){return d.correlation.getPageGUID()};return h}();d.vh=h})(k||(k={}));(function(d){d.beacons||(d.beacons={})})(k||(k={}));(function(d){(function(d){var a=function(){function b(){this.Nb=[];this.Oc={}}b.prototype.Pb=function(l){if(!l)return"";if(d.hasOwnPropertyDefined(this.Oc,l))return this.Oc[l];var e=this.Nb.length;this.Oc[l]=e;this.Nb[e]=l;return e};return b}();d.ne=a})(d.utils||(d.utils={}))})(k||
(k={}));(function(d){(function(h){var a=d.utils.map,b=function(){function d(){}d.xm=function(d){d=(d||"").match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]*)?(#[\s\S]*)?/);var c={};d[1]&&(c.protocol=d[1].substring(0,d[1].length-3));d[2]&&(c.path=d[2]);d[3]&&(c.Yl=d[3]);d[4]&&(c.anchor=d[4]);return c};d.Fj=function(e,c){var b=d.xm(e),h="";b.protocol&&(h+=c.Pb(b.protocol),h+="://");b.path&&(h+=a(b.path.split("/"),c.Pb,c).join("/"));return h+=a([b.Yl,b.anchor],function(d){return d?d[0]+c.Pb(d.slice(1)):""},c).join("")};
d.Dj=function(d,c){return""+c.Pb(d)};return d}();h.$d=b})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(h){(function(h){function b(){var c=null,l=null;try{c=localStorage[e]}catch(b){}if(c)try{c=l=JSON.parse(c),d.utils.isObject(c)&&d.utils.isNumber(c[f])&&-1<c[f]?k=l:d.error("M257")}catch(h){d.log(h,"M258");try{delete localStorage[e]}catch(g){d.log(g,"M259")}}}function l(){try{var l=d.channel,b=k[c]||k[g],h=l&&l.Y&&l.Y.X&&l.Y.X.id||(d.utils.isString(b)?b:d.utils.generateGUID());k[c]=
k[g]=h;localStorage[e]=d.utils.Ja(k)}catch(a){}}var e="ADRUM_CLIENTINFO",c="agentId",g="clientId",f="seqId",k;b();k||(k={seqId:0});l();h.ak=function(){b();var d=k[f]++;l();return d}})(h.Qe||(h.Qe={}))})(d.Kg||(d.Kg={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(){this.urlCapture={filterURLQuery:!1};this.wg=/;jsessionid=[^/?]+/;h.mergeJSON(this.urlCapture,d.conf.userConf.urlCapture);h.isBoolean(this.urlCapture.filterURLQuery)||h.isArray(this.urlCapture.filterURLQuery)||(d.log("M260"),
this.urlCapture.filterURLQuery=!1)}b.vm=function(d){for(var e=0,c=0;c<d.length;c++)e=(e<<5)-e+d.charCodeAt(c),e|=0;return e};b.prototype.kk=function(d){var e="",c,b;if(!h.isString(d))return"";c=d.indexOf("?")+1;0<c&&(b=d.indexOf("#"),0>b?e=d.substring(c):c<=b&&(e=d.substring(c,b)));return e};b.prototype.Kj=function(d){var e="",c=this.urlCapture.filterURLQuery,b={},a=0,k,m,p;if(!h.isString(d)||""===d)return"";if(!1===c)return d;k=this.kk(d);if(""===k)return d;if(h.isArray(c)){for(p=0;p<c.length;p++)b[c[p]]=
!0;c=k+"&";for(p=0;p<c.length;p++)switch(c[p]){case "=":m=c.substring(a,p);break;case "&":case ";":m=m||c.substring(a,p),p++,b[m]||(e+=c.substring(a,p)),a=p,m=null}e=e.substring(0,e.length-1)}""==e&&(k="?"+k);return d.replace(k,e)};b.prototype.sa=function(d){if(null===d||void 0===d)return null;if(""===d)return"";var e=d.match(this.wg),c=d;if(null!=e){var b=d.indexOf("?");if(0>b||b>e.index)c=d.replace(this.wg,"")}return c=this.Kj(c)};b.prototype.ff=function(d){if(null===d||void 0===d)return null;var e=
d.indexOf("?"),c=d.indexOf("#");0>e&&(e=Number.MAX_VALUE);0>c&&(c=Number.MAX_VALUE);return d.substring(0,Math.min(e,c))};b.prototype.Dl=function(d){if(null===d||void 0===d)return null;var e=this.ff(d);return e+"?"+b.vm(d.substring(e.length))};return b}();h.qn=a;h.Z=new a})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(h){(function(h){var b=function(){function b(e,c,l){var h=this;this.bm=0;this.zd=[];this.Af=!1;this.wk=l;d.utils.addEventListener(window,"message",function(d){h.Hl(d)});
this.vk=d.utils.rj(c,e)}b.prototype.Hl=function(e){var c;try{if(c=JSON.parse(e.data),"ADRUM_XD"!==c.name)d.log("M261");else if(!0===c.success)if(-1===c.id&&"iframe-ready"===c.data)this.Af=!0,this.wk();else{if(this.zd[c.id])this.zd[c.id](c.data)}else d.error("M262",e.data)}catch(b){d.log("M263",b)}};b.prototype.send=function(e,c,b,l){if(this.Af){var h=this.bm++;this.zd[h]=l;this.vk.contentWindow.postMessage(d.utils.Ja({id:h,action:e,key:c,value:b}),"*")}};b.prototype.generateGUID=function(d,c){this.send("generateGUID",
d,null,c)};return b}();h.Bh=b})(h.Vg||(h.Vg={}))})(d.mh||(d.mh={}))})(k||(k={}));(function(d){(function(h){var a=function(){function e(){this.Ge=new b(e.rh);this.lh=new b(e.th);this.cn=new l(e.sh)}e.prototype.init=function(c){this.channel=c;d.utils.Cm()&&d.utils.Bm()?d.utils.Dm()&&e.ll()?this.Nm():this.eh():e.fg=!0};e.prototype.eh=function(){var c=this.Ge.load();e.jl(c)||(c={ver:d.conf.agentVer,id:d.utils.generateGUID()},this.Ge.save(c));e.X=c};e.prototype.Nm=function(){var c=this,b=this.lh.load();
e.kl(b)?e.X=b:(d.log("M264"),this.cn.load(function(b){e.Qf(b)?(b={ver:d.conf.agentVer,id:b,ttl:(new Date).getTime()+e.Gh},c.lh.save(b),e.X=b,d.log("M265")):d.log("M266")}),d.utils.tryPeriodically(e.Ec,function(){return c.isReady()},function(){return c.onReady()},function(){return c.qd()}))};e.ll=function(){return d.conf.userConf&&d.conf.userConf.xd&&d.conf.userConf.xd.enable};e.jl=function(d){return d&&d.id&&0<d.id.length};e.kl=function(d){return d&&e.Qf(d.id)&&d.ttl>(new Date).getTime()};e.Qf=function(c){return d.utils.isString(c)&&
0<c.length&&0===c.indexOf("XD_")};e.prototype.isReady=function(){return e.fg||d.utils.isDefined(e.X)};e.prototype.onReady=function(){this.channel.onResolverReady()};e.prototype.qd=function(){d.log("M267");this.eh();this.channel.onResolverReady()};e.Ec=function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return e}();a.rh="ADRUM_AGENT_INFO";a.th="ADRUM_XD_AGENT_INFO";a.sh="ADRUM_XD_AGENT_ID";a.Gh=6048E5;a.fg=!1;h.Y=a;var b=function(){function e(d){this.Fe=d}e.prototype.load=function(){var c=null;try{var e=
localStorage.getItem(this.Fe);e&&(c=JSON.parse(e))}catch(b){d.exception(b,"M268")}return c};e.prototype.save=function(c){try{var e=d.utils.Ja(c);e&&localStorage.setItem(this.Fe,e)}catch(b){d.exception(b,"M269")}};return e}(),l=function(){function e(d){this.Wi=d}e.prototype.load=function(c){var e=this;try{var b=new d.mh.Vg.Bh("cross-domain-store-server-iframe",d.conf.adrumXdUrl,function(){b.generateGUID(e.Wi,c)})}catch(l){d.exception(l,"M270")}};return e}()})(d.channel||(d.channel={}))})(k||(k={}));
(function(d){(function(h){var a=d.utils.isString,b=d.utils.isNumber,l=function(){function e(){}e.prototype.Yb=function(c,b,l){c={ver:d.conf.agentVer,dataType:"R",rootGUID:l.Xc(),events:c};d.channel.Y.X&&d.channel.Y.X.id&&(c.agentId=d.channel.Y.X.id);b&&(c.geo=b);return e.Ql(c)};e.Ql=function(c){d.isDebug||(c=e.oj(c));return c};e.oj=function(c){var l=new d.utils.ne,f=new d.utils.ne;c=d.utils.Zc(null,c,e.Yc,function(c,k){if(!a(k))return k;if(e.il(c)){var p=e.cl(c)&&b(d.conf.userConf.maxUrlLength)?d.conf.userConf.maxUrlLength:
d.conf.Za;k=e.Jd(k,p);k=h.$d.Fj(k,l)}else k=e.bl(c)?e.Jd(k,d.conf.ab):e.Jd(k,d.conf.ji);e.Xk(c)&&(k=h.$d.Dj(k,f));return k},e.vl);c[e.Yc("guids")]=f.Nb;c[e.Yc("urlParts")]=l.Nb;return c};e.il=function(d){return"eventUrl"==d||"parentUrl"==d||"pageReferrer"==d||"pageUrl"==d||"u"==d};e.Xk=function(d){return"eventGUID"==d||"parentGUID"==d||"rootGUID"==d||"clientRequestGUID"==d};e.bl=function(d){return"userPageName"==d};e.Jd=function(d,e){return d.length>e?d.substr(0,e-3)+"...":d};e.cl=function(d){return"eventUrl"==
d||"parentUrl"==d||"pageReferrer"==d};e.Yc=function(c){if(d.conf.useDebugBeaconParams)return c;var e=d.conf.Xf[c];return"undefined"===typeof e?c:e};e.vl=function(d){d=""+d;return 0===d.indexOf("userData")||"parameter"===d};return e}();h.yh=l})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.send=function(d,e){for(var c=0;c<d.length;c++)this.mm(d[c],e)};b.prototype.mm=function(b,e){var c=(e?d.conf.beaconUrlHttps:d.conf.beaconUrlHttp)+d.conf.imageEndpointPath,
a=document.createElement("img");a.J=!0;try{a.src=c+b}catch(f){}d.isDebug&&h.beaconsSent.push(b);h.numBeaconsSent+=1};return b}();h.Wh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){d.xb=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,b-3)+"...");return d};d.$g=function(d,b){if(3>=b)return"...";d.length>b&&(d=d.substring(0,(b-3)/2)+"..."+d.substring(d.length-(b-3)/2,d.length));return d};d.Jm=function(a,b){a.length<=b||(a=d.xb(a,b-1),a+=":");return a};d.Hm=function(a,
b,l,e,c,g){a=d.Jm(a,e);l=d.xb(l,c);a.length+b.length+l.length>g-3&&(b=d.xb(b,g-3-a.length-l.length));return 0<l.length?a+"//"+b+":"+l:a+"//"+b};d.Im=function(a,b,l){a=d.map(a,function(e){return d.$g(e,b)});if(a.length>l){var e=a[0];a=a.slice(a.length-l);a.unshift("...");""==e&&a.unshift(e)}return a};d.Km=function(a,b,l,e,c){e=d.Hm(a.protocol,a.hostname,a.port,e,c,b);l--;c=d.xb(a.search,b);l--;var g=d.xb(a.hash,b);l--;a=a.pathname.split("/");var f="";0<a.length&&(f=a.pop(),f=d.$g(f,b),l--);a=d.Im(a,
b,l);return 0==a.length?e+f+c+g:e+a.join("/")+"/"+f+c+g}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.dd=function(){for(var l=0;l<d.ge.length;l++)d.na[d.ge[l]]=d.ea.Qh;for(l=0;l<d.de.length;l++)d.na[d.de[l]]=d.ea.Kh;d.na.js=d.ea.Di;d.na.css=d.ea.CSS;d.na.svg=d.ea.Fi;d.na.html=d.ea.fe;d.na.htm=d.ea.fe};d.Uc=function(d){return d.duration?d.duration:d.responseEnd&&d.startTime?d.responseEnd-d.startTime:-1};d.wf=function(l){var e;return(l=l.pathname)&&
-1!=(e=l.lastIndexOf("."))?d.na[l.substring(e+1,l.length).toLowerCase()]||d.ea.OTHER:d.ea.OTHER};return d}();a.ea={Qh:"img",Di:"script",CSS:"css",Fi:"svg",fe:"html",Kh:"font",OTHER:"other"};a.ge="bmp gif jpeg jpg png webp".split(" ");a.de=["ttf","woff","otf","eot"];a.na={};d.bb=a;a.dd()})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(l){function e(d){c.marks.push(0==l[d]?-1:Math.round(l[d]-c.ig))}this.marks=[];var c=this;this.ig=l.startTime;this.Uk(l)?
(this.jf=d.ae,e("startTime"),e("fetchStart")):(this.jf=d.ve,e("startTime"),e("redirectStart"),e("redirectEnd"),e("fetchStart"),e("domainLookupStart"),e("domainLookupEnd"),e("connectStart"),e("secureConnectionStart"),e("connectEnd"),e("requestStart"),e("responseStart"));e("responseEnd")}d.ck=function(){var l={};l[d.ve]=d.Ci;l[d.ae]=d.Ah;return l};d.prototype.Uk=function(d){return this.Da(d.redirectStart)&&this.Da(d.redirectEnd)&&(this.Da(d.domainLookupStart)||this.Da(d.domainLookupEnd)||this.Da(d.connectStart)||
this.Da(d.connectEnd))&&this.Da(d.secureConnectionStart)};d.prototype.Da=function(d){return!d||0===d};return d}();a.ve=1;a.ae=2;a.Ci="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart secureConnectionStart connectEnd requestStart responseStart responseEnd".split(" ");a.Ah=["startTime","fetchStart","responseEnd"];d.ue=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.hc=function(d,e){if(d)return d.slice(0,
e)};return d}();d.Lh=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(){function b(){}b.prototype.hc=function(b,e){if(b){if(b.length<=e)return b;for(var c=[],a=0;a<b.length;a++)c.push({Ad:b[a],index:a});c.sort(function(e,c){return-(d.bb.Uc(e.Ad)-d.bb.Uc(c.Ad))});c=c.slice(0,e);c.sort(function(d,e){return d.index-e.index});for(var f=[],a=0;a<c.length;a++)f.push(c[a].Ad);return f}};return b}();d.xe=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=
function(){function b(){}b.prototype.hc=function(b,e){if(b){if(b.length<=e)return b;for(var c=1,a=Math.floor(Number.MAX_VALUE/4),f=b.length;c<a;){for(var k=b.length-1;0<=k;k--)if(d.bb.Uc(b[k])<c&&(b.splice(k,1),f--),f<=e)return b;c*=4}return(new d.xe).hc(b,e)}};return b}();d.Bi=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,b=function(){function e(c,b,a){this.version=2;this.resourceTimingInfo={};this.Df={};this.Ef={};this.Ag={};this.Bg={};this.Bd=
[];this.Qi=function(e,c,b){if(e&&c&&0<c.length){this.Fm=e;for(var a=new l,g=new l,k=0;k<c.length;k++){var f=c[k],n=d.utils.parseURI(d.utils.Z.sa(f.name)),u=f.initiatorType,C=h.bb.wf(n),z=new h.ue(f);this.Bd.push({u:this.Lm(n),i:a.rf(this.Ef,u),r:g.rf(this.Bg,C),f:z.jf,o:this.Vj(0===k&&f.isBase,z.ig,e,b),m:z.marks,e:d.utils.isDefined(f.encodedBodySize)?f.encodedBodySize:-1,d:d.utils.isDefined(f.decodedBodySize)?f.decodedBodySize:-1,s:d.utils.isDefined(f.transferSize)?f.transferSize:-1,p:d.utils.isDefined(f.nextHopProtocol)?
f.nextHopProtocol:""})}}};var k=e.Wj();this.kj(k,c);c=this.im(k,c);this.Qi(b||d.monitor.navMonitor.navTiming&&d.monitor.navMonitor.navTiming.navigationStart,c,a);this.clearResourceTimings()}e.dd=function(){var c=d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.sampler;e.hm=c&&"FirstN"==c?new h.Lh:c&&"TopN"==c?new h.xe:new h.Bi};e.prototype.Bf=function(d,e){d[e]=d[e]?d[e]+1:1};e.prototype.Lm=function(e){return d.utils.Km(e,"number"===typeof d.conf.userConf.maxResUrlSegmentLength?
d.conf.userConf.maxResUrlSegmentLength:d.conf.Eh,"number"===typeof d.conf.userConf.maxResUrlSegmentNumber?d.conf.userConf.maxResUrlSegmentNumber:d.conf.Fh,d.conf.ri,d.conf.qi)};e.prototype.kj=function(d,e){d&&this.Cf(d);if(e&&0<e.length)for(var b=0;b<e.length;b++)this.Cf(e[b])};e.prototype.Cf=function(e){var b=d.utils.parseURI(d.utils.Z.sa(e.name)),b=h.bb.wf(b);this.Bf(this.Df,e.initiatorType);this.Bf(this.Ag,b)};e.prototype.im=function(c,b){if(b&&0<b.length){var l=d.conf.userConf&&d.conf.userConf.resTiming&&
d.conf.userConf.resTiming.maxNum||d.conf.mi;c&&l--;b=e.hm.hc(b,l);c&&b.unshift(c)}return b};e.prototype.Vj=function(e,b,l,h){return e?1:d.utils.isDefined(h)?Math.round(b+l-h):Math.round(b)};e.prototype.build=function(){return 0==this.Bd.length?null:{v:this.version,ic:this.Df,it:this.Ef,rc:this.Ag,rt:this.Bg,f:h.ue.ck(),t:this.Fm,r:this.Bd}};e.Wj=function(){var e=d.monitor.navMonitor.navTiming,b=null;if(e){var b={},l;for(l in e)a(e,l)&&(b[l]=e[l]);b.initiatorType="other";b.name=document.URL;b.navigationStart&&
!b.startTime&&(b.startTime=b.navigationStart);b.isBase=!0}return b};e.prototype.clearResourceTimings=function(){d.conf.userConf&&d.conf.userConf.resTiming&&d.conf.userConf.resTiming.clearResTimingOnBeaconSend&&d.monitor.resourceMonitor.clearResourceTimings()};return e}();h.ResourceTimingInfoBuilder=b;var l=function(){function d(){this.xl=1}d.prototype.rf=function(d,e){d[e]||(d[e]=this.xl++);return d[e]};return d}();b.dd()})(d.events||(d.events={}))})(k||(k={}));(function(d){d.events||(d.events={})})(k||
(k={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.G=function(b,e){void 0===e&&(e={});var c={eventGUID:b.guid(),eventType:b.type(),eventUrl:d.utils.Z.sa(b.url()||document.URL),timestamp:d.utils.now()};b.type()!==d.EventType.PageView&&d.utils.mergeJSON(c,{parentGUID:b.parentGUID()||d.correlation.getPageGUID(),parentUrl:d.utils.Z.sa(b.parentUrl()||document.URL),parentType:b.parentType()||(d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME)});var a=d.EventType[b.type()],
a=h.fa.sk(a,d.conf.userConf,e,d.conf.$a),k;for(k in a)c[k]=a[k];return c};return b}();h.Xa=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=d.utils.isNumber,b=d.utils.isString,l=d.utils.isObject,e=d.utils.Ve,c=d.utils.gd,g=d.utils.isBoolean,k=function(){function c(){}c.od=function(e,c){var b=!1;if(l(e)){var h=d.utils.Ja(e);if(!h||h.length<=c)b=!0}return b};c.Hd=function(d,e,l){if(b(e))if(e.length>l)c.Ra(d,l,e.length);else return e;else c.jd(d,"string")};c.ac=function(d,e){return function(b,
h,a){if(l(h)){var k,g;for(g in h)d(h[g])?(k=k||{},k[g]=h[g]):c.jd(b,e,g);if(k){if(c.od(k,a))return k;c.Ra(b,a)}}else c.jd(b,"object")}};c.jd=function(d,c,b){e(d+" dropped because it was not a "+c+(b?", field name "+b:""))};c.Ra=function(d,c,b){e("User event info field "+d+" dropped because it is too long"+(b?" ("+b+" exceeds "+c+")":""))};return c}();k.sk=function(e,c,b,h){if(c=c&&c.userEventInfo&&c.userEventInfo[e]){try{var a=d.utils.isFunction(c)?c.call(null,b):c}catch(g){d.exception(g,"M272",e),
y.error("Error detected executing adrum userEventInfo")}if(l(a))return k.Um(a,h)}};k.Um=function(d,e){var c={},b;for(b in k.gf)if(b in d){var l=k.gf[b](b,d[b],e);l&&(c[b]=l)}return c};k.Gl=k.ac(b,"string");k.Fl=k.ac(c,"integer");k.gg=k.ac(a,"number");k.El=k.ac(g,"boolean");k.gf={userPageName:k.Hd,userData:k.Gl,userDataLong:k.Fl,userDataDouble:k.gg,userDataBoolean:k.El,userDataDate:k.gg};h.fa=k})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=d.utils.isDefined,b=function(b){function e(){return null!==
b&&b.apply(this,arguments)||this}v(e,b);e.setPageName=function(d){e.ta=d};e.addUserData=function(d,b){e.yb=e.yb||{};e.yb[d]=b};e.prototype.G=function(c){var k=b.prototype.G.call(this,c||new h.PageView),f=this.ek(),n=this.Xj();d.conf.viz&&(f&&d.utils.Nc(document.getElementById(d.conf.viz),f,"navtime"),d.utils.Nc(document.getElementById(d.conf.viz),n,"cookie"));n.PLC=1;f&&(f.PLC=1,f.VCT=d.utils.isDefined(c)?c.vct:0,d.conf.spa2&&(f.PCT=d.utils.isDefined(c)?c.pct:0));d.monitor.ErrorMonitor.hadErrors&&
(n.EPM=1,f&&(f.EPM=1));d.utils.mergeJSON(k,{eventGUID:d.correlation.getPageGUID(),eventType:d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME,cookieMetrics:n});c=-1;f&&f.timestamp?c=f.timestamp:n&&n.timestamp&&(c=n.timestamp);0<c&&d.utils.mergeJSON(k,{timestamp:c});f&&(k.metrics=f);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(k.pageReferrer=d.utils.Z.sa(document.referrer));f=e.hk();0<f.length&&(k.pageTitle=f);f=d.correlation.yf();null!==f&&(k.serverMetadata=
f);f=0<d.monitor.resourceMonitor.basePageResourceBuffer.length?(new h.ResourceTimingInfoBuilder(d.monitor.resourceMonitor.basePageResourceBuffer)).build():null;null!==f&&(k.resourceTimingInfo=f);!a(k.userData)&&a(e.yb)&&(h.fa.od(e.yb,d.conf.$a)?k.userData=e.yb:h.fa.Ra("userData",d.conf.$a));!a(k.userPageName)&&a(e.ta)&&(h.fa.Hd("userPageName",e.ta,d.conf.ab)?k.userPageName=e.ta:h.fa.Ra("userPageName",d.conf.ab));e.userPageName=k.userPageName;return k};e.prototype.ek=function(){if(!d.monitor.navMonitor.navTiming)return null;
var c={},b=e.tf(d.monitor.navMonitor.navTiming,c,"NT"),l=h.metricSpec[d.EventType.PageView],a;for(a in l){var k=l[a];b.add(k.name,k.start,k.end)}c.timestamp=d.monitor.navMonitor.navTiming.navigationStart;return c};e.prototype.Xj=function(){var b={};d.commands.marks&&(e.tf(d.commands.marks,b,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready"),b.timestamp=
d.commands.marks.starttime?d.commands.marks.starttime:d.commands.marks.firstbyte);return b};e.hk=function(){var e=d.conf.userConf,e=e&&e.page,b;b=e&&"captureTitle"in e?e.captureTitle:!0;var l,h;e&&(l="title"in e,h=e.title);l=b?l?d.utils.isFunction(h)?h():h:document.title:"";if(d.utils.isString(l))return l;d.utils.Ve("Ignoring wrong type of page title: "+typeof l);return""};e.Oi=function(e,b,l,h,a,k){b=h[b];l=h[l];b&&l?a[e]="DPT"!==e?l-b:Math.max(l-b,0):d.log("M273",k,e,b,l)};e.tf=function(d,b,l){var h=
{add:function(a,k,r){e.Oi(a,k,r,d,b,l);return h}};return h};return e}(h.Xa);h.oa=b})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){(function(h){function b(c,h){var a,u=h[c],n=typeof u;t.push(c);var p=q[t.join(".")];if(d.utils.isFunction(p))a=p(u);else switch(n){case "string":a="number"==typeof p?m(u,e,p):e(u);break;case "number":a=f(u);break;case "object":if(u)if(d.utils.isArray(u))a=k(u,!1,!1);else{a=[];for(var A in u)r(u,A)&&(n=b(A,u))&&(l(c)&&"timestamp"==A||a.push({Wb:A,v:n}));
if(l(c)){for(u=0;u<a.length;u++)a[u]=a[u].Wb+e(":")+a[u].v;a=e("{")+a.join(e(","))+e("}")}else{for(u=0;u<a.length;u++)A=a[u],n=A.Wb,d.conf.useDebugBeaconParams||((p=d.conf.Xf[A.Wb])?n=p:d.error("M274",A.Wb)),a[u]=n+"="+A.v;a=a.join("&")}}else a=null}t.pop();return a}function l(d){return"navOrXhrMetrics"==d||"cookieMetrics"==d}function e(d){return"undefined"===typeof d||null===d||0===d.length?null:encodeURIComponent(d)}function c(d){return encodeURIComponent(encodeURIComponent(d))}function k(d,c,h){void 0===
c&&(c=!1);void 0===h&&(h=!0);if(0===d.length)return null;var l=[];if(c)l=d;else for(c=0;c<d.length;c++)l.push(b(c,d));return e("[")+l.join(e(","))+e(h?">":"]")}function f(d){d=Math.round(d);d<h.se&&(d=h.se);d>h.pe&&(d=h.pe);return e(d)}function n(d,b){if(d>b||0>d)d=h.vi;return e(d)}function m(e,b,c,h){void 0===h&&(h=!0);if("undefined"===typeof e||null===e||0===e.length)return null;var l=3<=c?"...":"";d.assert(c>=l.length);for(var a=!1,k=null;;){try{k=b(e);if(null===k)return null;if(k.length<=c)break}catch(g){}var f;
a?f=e.length-1:(a=!0,f=c-=l.length);var n=h?0:Math.max(e.length-f,0);e=e.substr(n,f)}a&&(k=h?k+l:l+k);return k}function p(e,b,c){if(0==c)return h.xc;if(b<e)return 0;b=h.xc+(b-e)/c;d.assert(b>=h.xc);d.log("M275",e,b);return b}var r=d.utils.hasOwnPropertyDefined;h.vi=-1;h.Za=180;h.oi=50;h.pi=50;h.ii=40;h.xc=50;h.Xh=50;h.re=128;h.di=30;h.ei=30;h.ci=30;h.ki=8;h.se=-99999;h.pe=999999;h.Yh=2E3;h.ni=2;h.Zh=99999999;var q={".pageUrl":h.Za,".parentPageUrl":h.Za,".pageReferrer":h.Za,".pageTitle":h.oi,".userPageName":h.pi,
".geoCountry":h.di,".geoRegion":h.ei,".geoCity":h.ci,".localIP":h.ki,".otherClientRequestGUIDs":function(d){d=d||[];var e=d.slice(0,h.ni);return k(e,!1,e.length<d.length)},".btTime":function(e){e=e||[];for(var b=e.slice(0,d.conf.$h),c=[],l=0;l<b.length;l++){var p=b[l];c.push(k([n(Number(p[0]),h.Zh),f(p[1]),f(p[2])],!0,!1))}return k(c,!0,b.length<e.length)},".ajaxError":function(d){return k([c(d[0]),m(d[1],c,h.Xh)],!0,!1)},".userData":function(d){d=d||[];for(var e=!1,b=0,l=[],f=0;f<d.length;f++){var n=
d[f];l[f]=k([c(n[0]),c(n[1])],!0,!1);b+=l[f].length;if(b>h.re){e=!0;break}}for(;;){d=k(l,!0,e);if(null===d||d.length<=h.re)return d;l.pop();e=!0}}},t=[];h.Cj=function(e,l){void 0===l&&(l=!0);t=[];var n=[];e.errors&&(n=e.errors,e.errors=null);var q=b("",{"":e});if(n&&0<n.length){for(var r=p(l?870:354,h.Yh-q.length,n.length),v=[],A=0;A<n.length;A++){var D=n[A],B=d.utils.Z.ff(d.utils.Z.sa(D[0]));v.push(k([m(B,c,h.ii,!1),d.utils.gd(D[1])?f(D[1]):-1,m(D[2],c,r)],!0,!1))}n=k(v,!0,!1);q+="&errors="+n}return q};
h.In=b;h.qo=e;h.element=c;h.An=k;h.Cn=f;h.eo=n;h.truncate=m;h.mo=p})(h.me||(h.me={}))})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,b=d.utils.Lb,l=function(){function e(){}e.prototype.Yb=function(b,l,a){for(var k=[],m=[],p=null,r=[],q=0;q<b.length;q++){var t=b[q];if(t.eventType===d.EventType.Error){var v=t;m.push([t.eventUrl+"",d.utils.gd(v.line)?v.line:void 0,v.message+""])}else{if(t.eventType===d.EventType.PageView||t.eventType===d.EventType.IFRAME)p=
t;r.push(t)}}b=r;if(0<m.length)for(p&&(p.errors=m.splice(0,d.conf.gi));0<m.length;)t=m.splice(0,d.conf.fi),p=e.Jl.G(),p.errors=t,p.isErrorEvent=!0,p.cookieMetrics=null,p.metrics=null,p.resourceTimingInfo=null,b.push(p);for(m=0;m<b.length;m++)t=b[m],d.log("M276"),t.resourceTimingInfo=null,e.Pj(t,l,a),p=e.transform(t),k.push(h.me.Cj(p,t.isErrorEvent));return k};e.Pj=function(e,b,h){e.ver=this.Rh;e.rootGUID=h.Xc();e.geo=b;e.dataType="R";e.eom=1;e.eumAppKey=d.conf.appKey;e.PLC=1};e.transform=function(d){var b=
{};e.hh("",{"":d},b);return b};e.hh=function(c,h,l){h=h[c];var k=e.Uf[c];if("metrics"===c||"cookieMetrics"===c)l[k]=h;else if("btTime"===c&&d.utils.isArray(h)&&0<h.length){c=[];for(var m=0;m<h.length;m++)c.push([h[m].id,h[m].duration,h[m].ert]);l[k]=c}else if("userData"===c&&d.utils.isObject(h))l[k]=d.utils.sl(h);else if(!(c&&-1<b(["userDataLong","userDataDouble","userDataBoolean","userDataDate"],c)))if(d.utils.isObject(h))for(m in h)a(h,m)&&e.hh(m,h,l);else e.Uf[c]&&("eventType"===c&&h>d.EventType.Ajax&&
(h=d.utils.compareWindows(top,window)?d.EventType.PageView:d.EventType.IFRAME),l[k]=h)};return e}();l.Jl=new d.events.oa;l.Rh=3;l.Uf={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",
cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};h.Vh=l})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.send=
function(){};return d}();d.Jh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(d){var a=function(){function d(){}d.prototype.Yb=function(){return null};return d}();d.Ih=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(d){this.nl=d}b.prototype.send=function(b){try{this.nl.postMessage(d.utils.Ja(b)),d.log("M277"),h.numBeaconsSent+=1}catch(e){d.log("M278")}};return b}();h.Oh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){(function(h){var a=
function(){function b(){}b.prototype.Yb=function(b,e,c){b={ver:d.conf.agentVer,dataType:"R",rootGUID:c.Xc(),events:b};d.channel.Y.X&&d.channel.Y.X.id&&(b.agentId=d.channel.Y.X.id);e&&(b.geo=e);return b};return b}();h.Nh=a})(d.beacons||(d.beacons={}))})(k||(k={}));(function(d){var h=function(){function h(){}h.Se=function(b,h){if(!b)return null;var e=b.ADRUM.lifecycle;if(!e||!e.getPhaseCallbackTime)return null;var c=h.getPhaseCallbackTime("AT_ONLOAD"),e=e.getPhaseCallbackTime("AT_ONLOAD"),a=null==e;
return null==c?(d.error("M279"),null):d.lifecycle.getPhaseID(a||c<=e?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return h}();d.yi=h;d.cPLPI=h.Se})(k||(k={}));(function(d){(function(h){var a=function(){function b(b){this.ready=!1;this.geoResolverUrl=b;d.utils.isString(b)&&0<d.utils.trim(b).length&&(this.geoResolverUrl=b+"/resolve.js")}b.prototype.init=function(b){this.channel=b;if(this.Jc()&&(d.geo=this.Md(),this.Xi()||this.dc()&&!this.lf())){this.channel.Cd(d.geo.result);return}this.lf()?(this.dc()&&(this.geoResolverUrl+=
"?ip="+encodeURIComponent(d.conf.userConf.geo.localIP)),this.Rm()):(this.ready=!0,this.channel.onResolverReady())};b.prototype.Jc=function(){return d.utils.isDefined(d.conf.userConf)&&d.utils.isDefined(d.conf.userConf.geo)};b.prototype.dc=function(){return this.Jc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&!d.utils.isDefined(d.conf.userConf.geo.city)&&!d.utils.isDefined(d.conf.userConf.geo.region)&&!d.utils.isDefined(d.conf.userConf.geo.country)};b.prototype.Md=function(){return{failed:!1,
result:{country:d.conf.userConf.geo.country,region:d.conf.userConf.geo.region,city:d.conf.userConf.geo.city,localIP:this.Ej(d.conf.userConf.geo.localIP)}}};b.prototype.Xi=function(){return this.Jc()&&d.utils.isDefined(d.conf.userConf.geo.localIP)&&d.utils.isDefined(d.conf.userConf.geo.city)&&d.utils.isDefined(d.conf.userConf.geo.region)&&d.utils.isDefined(d.conf.userConf.geo.country)};b.prototype.lf=function(){return d.utils.isString(this.geoResolverUrl)&&0<d.utils.trim(this.geoResolverUrl).length};
b.prototype.Ej=function(d){if(null==d||0==d.length)return null;d=d.split(".");if(4!=d.length)return null;for(var e=[],b=0;b<d.length;b++){var h=parseInt(d[b]);if(isNaN(h)||0>h||255<h)return null;e.push(("0"+h.toString(16)).slice(-2))}return e.join("")};b.prototype.Rm=function(){d.geo={failed:!1,result:null};d.utils.loadScriptAsync(this.geoResolverUrl);var h=this;d.utils.tryPeriodically(b.Ec,function(){return h.isReady()},function(){h.onReady()},function(){h.qd()})};b.prototype.isReady=function(){this.ready||
(this.ready=d.geo&&(d.geo.failed||null!==d.geo.result))||d.log("M280");return this.ready};b.prototype.onReady=function(){d.geo.failed?(d.log("M281"),this.dc()&&(d.geo=this.Md())):(d.assert("object"===typeof d.geo.result),d.log("M282",d.geo.result));d.geo&&d.geo.result&&this.channel.Cd(d.geo.result);this.channel.onResolverReady()};b.prototype.qd=function(){d.log("M283");this.dc()&&(d.geo=this.Md());d.geo&&d.geo.result&&this.channel.Cd(d.geo.result);this.ready=!0;this.channel.onResolverReady()};b.Ec=
function(d){return 10<d?-1:[1,50,100,500][d-1]||1E3};return b}();h.Mh=a})(d.channel||(d.channel={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(){this.ready=!1;this.channel=null}b.prototype.init=function(h){this.channel=h;b.aa=b.aa||b.Sj();this.ready=!b.aa.Tb;var e=this;if(b.aa.Tb)d.log("M284"),b.aa.Tb.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){d.log("M285");e.ready=!0;e.onReady()});else e.onReady()};b.prototype.isReady=function(){this.isReady||d.log("M286");
return this.ready};b.prototype.onReady=function(){this.channel.nm(b.aa);this.channel.onResolverReady()};b.Sj=function(){for(var h=window,e,c=b.Sf(h),a=window;a.parent&&!d.utils.compareWindows(a,a.parent);){a=a.parent;c=c||b.Sf(a);try{a.ADRUM&&(e=e||a,h=a)}catch(k){}}return new d.vh(e,h,c)};b.Sf=function(d){try{return 0==d.document.URL.indexOf("https:")}catch(e){}};return b}();a.aa=null;h.wh=a})(d.channel||(d.channel={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(e,c,l){this.events=
[];this.Ba={};this.Ob=NaN;this.ra=[];this.Tc=!1;this.bufferMode=d.conf.userConf&&d.conf.userConf.channel&&"undefined"!==typeof d.conf.userConf.channel.bufferMode?d.conf.userConf.channel.bufferMode:!0;this.jc=-1;this.Gm=e;this.ej=c;this.ra.push(new h.Mh(l));this.ra.push(new h.wh);this.ra.push(new h.Y)}b.create=function(){var e,c;e=b.Ol();d.utils.isDefined(e)?(e=new d.beacons.Oh(e),c=new d.beacons.Nh):d.utils.isCORSSupported()&&!d.conf.sendImageBeacon?(e=new d.beacons.zh,c=new d.beacons.yh):d.conf.neverSendImageBeacon?
(d.log("M287"),e=new d.beacons.Jh,c=new d.beacons.Ih):(e=new d.beacons.Wh,c=new d.beacons.Vh);e=new b(e,c,d.conf.geoResolverUrl);e.init();return e};b.prototype.init=function(){for(var d=0;d<this.ra.length;d++)this.ra[d].init(this)};b.prototype.Xm=function(b){return(b.parentType===d.EventType.VPageView||b.parentType===d.EventType.NG_VIRTUAL_PAGE)&&null!==this.Ba[b.parentGUID]};b.prototype.vd=function(b){var c=b.parentGUID;if(!d.utils.isDefined(this.Ba[c])){this.Ba[c]=[];var h=this,l=b.eventGUID;d.utils.oSTO(function(){h.Mc(l)},
1E4)}this.Ba[c].push(b)};b.prototype.report=function(e){e.sequenceId=d.Kg.Qe.ak();e.timestamp=e.timestamp||d.utils.now();this.Xm(e)?this.vd(e):this.events.push(e);1==this.events.length&&(this.Ob=d.utils.now());var c=e.parentGUID;c&&c!==d.correlation.getPageGUID()||this.Mc(e.eventGUID);b.Yk(e)&&(this.Tc=!0);this.Kd()};b.prototype.Mc=function(d){var b=this.Ba[d];this.Ba[d]=null;if(b&&0!=b.length)for(this.events=this.events.concat(b),d=0;d<b.length;d++)this.Mc(b[d].eventGUID)};b.prototype.al=function(b){return b.eventType===
d.EventType.PageView||b.eventType===d.EventType.IFRAME};b.prototype.fj=function(){for(var b=0;b<this.events.length;b++){var c=this.events[b];if(this.al(c)){var h=this.aa.Tb;h&&(c.parentLifecyclePhase=d.yi.Se(h,d.lifecycle),c.parentGUID=h.ADRUM.correlation.getPageGUID(),c.parentUrl=d.utils.Z.sa(h.document.URL),d.utils.isDefined(h.ADRUM.events.oa.userPageName)&&(c.Kl=h.ADRUM.events.oa.userPageName),c.parentType=d.utils.compareWindows(top,h)?d.EventType.PageView:d.EventType.IFRAME)}}};b.prototype.km=
function(){if(0==this.events.length)d.log("M288");else{this.fj();var b=this.Nd(this.events,this.aa),c=this.ej.Yb(this.events,this.Rj,this.aa);this.Gm.send(c,b);this.events=[];this.Ob=Number.POSITIVE_INFINITY}};b.prototype.onResolverReady=function(){this.Kd()};b.prototype.Cd=function(d){this.Rj=d};b.prototype.nm=function(d){this.aa=d};b.prototype.addResolver=function(d){d.init(this);this.ra.push(d)};b.prototype.em=function(){for(var d=0;d<this.ra.length;d++)if(!this.ra[d].isReady())return!1;return!0};
b.prototype.Tf=function(){return this.Ob+d.conf.oe>d.utils.now()};b.prototype.fl=function(){return this.events.length<d.conf.ai};b.prototype.Nd=function(b,c){if(c.Nd||d.conf.userConf.useHTTPSAlways)return!0;for(var h=0;h<b.length;h++){var l=b[h];if(l.eventUrl&&0==l.eventUrl.indexOf("https:"))return!0}return!1};b.prototype.getEventsWithParentGUID=function(d){return this.Ba[d]||[]};b.prototype.Kd=function(){if(this.em())if(this.Wm()){if(this.Tf()&&0<this.events.length&&0>this.jc){var b=this;this.jc=
d.utils.oSTO(function(){b.Kd()},d.conf.oe+this.Ob-d.utils.now())}}else clearTimeout(this.jc),this.jc=-1,this.Tc=!1,this.km()};b.Yk=function(b){return b.eventType===d.EventType.PageView||b.eventType===d.EventType.IFRAME||b.eventType===d.EventType.VPageView};b.prototype.Wm=function(){return this.bufferMode&&!this.Tc&&this.fl()&&this.Tf()};b.Pl=function(){if(d.utils.isDefined(window.webkit)&&d.utils.isDefined(window.webkit.messageHandlers)&&d.utils.isDefined(window.webkit.messageHandlers.ADEUM_js_handler)&&
d.utils.isFunction(window.webkit.messageHandlers.ADEUM_js_handler.postMessage))return window.webkit.messageHandlers.ADEUM_js_handler};b.Nl=function(){if(d.utils.isDefined(window.ADEUM_js_handler)&&d.utils.isFunction(window.ADEUM_js_handler.postMessage))return window.ADEUM_js_handler};b.Ol=function(){return b.Nl()||b.Pl()};return b}();h.Channel=a;var b=a.create();h.report=function(d){b.report(d)};h.addResolver=function(d){b.addResolver(d)};h.getEventsWithParentGUID=function(d){return b.getEventsWithParentGUID(d)}})(d.channel||
(d.channel={}))})(k||(k={}));(function(d){var h=function(){function h(){}h.qg=function(){return window.attachEvent?d.utils.isFunction(window.addEventListener)?this.Od:this.Xg:this.bh};h.pg=function(b){var l=null;switch(h.qg()){case h.bh:l=b.parentPhase();break;case h.Od:l=d.lifecycle.findPhaseAtNominalTime(b.getSendTime());break;case h.Xg:l=null}return d.lifecycle.getPhaseID(l)};return h}();h.bh="uCT";h.Od="uNET";h.Xg="tIA";d.Hb=h})(k||(k={}));(function(d){(function(h){var a=d.utils.hasOwnPropertyDefined,
b=function(b){function e(){return null!==b&&b.apply(this,arguments)||this}v(e,b);e.prototype.G=function(c){var a=b.prototype.G.call(this,c,e.getContext(c)),k=c.url(),n=c.getSendTime(),m=c.getFirstByteTime(),p=c.getRespAvailTime(),r=c.getRespProcTime(),q=c.parentPhase();d.assert(null!==k&&null!==n&&null!==m&&null!==p&&null!==r,"M289",k,n,m,p,r,q);if(null===k||null===n||null===m||null===p||null===r)return null;k=c.error();n={PLC:1,FBT:m-n,DDT:p-m,DPT:r-p,PLT:r-n,ARE:k?1:0};m=c.url();if(!e.ml(n,m))return null;
d.conf.viz&&d.utils.Nc(document.getElementById(d.conf.viz),n,"xhr");d.utils.mergeJSON(a,{eventUrl:d.utils.Z.sa(m),parentLifecyclePhase:c.parentPhaseId(),metrics:n,method:c.method(),timestamp:c.timestamp(),ajaxError:k&&[k.status,k.msg||""],xhrStatus:c.xhrStatus()});(c=c.parameter())&&h.fa.od(c,d.conf.$a)?a.parameter=c:c&&h.fa.Ra("parameter",d.conf.$a);a.parentType==d.EventType.VPageView&&d.conf.spa2?d.utils.Lg(a,h.Cb.userPageName):d.utils.Lg(a,h.oa.userPageName);return a};e.getData=function(b){if(d.utils.isDefined(b)&&
d.utils.isDefined(b.data))return b.data};e.getContext=function(d){return{url:d.url()||"",method:d.method()||"",data:e.getData(d.dataObject())||""}};e.ml=function(b,e){for(var h in b)if(a(b,h)){var l=b[h];if(0>l)return d.error("M290",h,l,e),!1}return!0};return e}(h.Xa);h.ze=b})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=function(b){function h(){return null!==b&&b.apply(this,arguments)||this}v(h,b);h.prototype.G=function(e){var h=b.prototype.G.call(this,e);h&&(e=e.allResponseHeaders()||
"",(e=d.correlation.pk(e))&&null!==e&&null!==e.clientRequestGUID&&(h.eventGUID=e.clientRequestGUID),null!==e&&(h.serverMetadata=e));return h};return h}(h.ze);h.qh=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=function(b){function l(){return null!==b&&b.apply(this,arguments)||this}v(l,b);l.prototype.G=function(e){var c=b.prototype.G.call(this,e);d.utils.mergeJSON(c,{message:e.msg()||"",timestamp:e.timestamp(),line:e.line(),stack:e.stack(),parentPageName:c.parentType==d.EventType.VPageView&&
d.conf.spa2?h.Cb.userPageName:h.oa.userPageName});d.utils.isString(c.userPageName)||(c.userPageName=c.Kl);return c};return l}(h.Xa);h.xi=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){(function(a){a.build=function(b){var l={},e=d.metricSpec[b.type()],c;for(c in e){var a=e[c];if(null!==a.name&&b.perf.getEntryByName(a.start)&&b.perf.getEntryByName(a.end)){b.perf.measure(a.name,a.start,a.end);var k=b.perf.getEntryByName(a.name);l[a.name]=k&&0<=k.duration&&k.duration||null}}for(c in l)l[c]=
Math.round(l[c]);return l}})(d.yc||(d.yc={}))})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(b){function a(){return null!==b&&b.apply(this,arguments)||this}v(a,b);a.prototype.G=function(e){var c=b.prototype.G.call(this,e),a=d.yc.build(e);a.PLC=1;c.metrics=a;c.timestamp=e.timestamp();e=(new d.ResourceTimingInfoBuilder(e.resTiming())).build();null!==e&&(c.resourceTimingInfo=e);return c};return a}(d.Xa);d.ye=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(h){var a=
function(b){function a(){return null!==b&&b.apply(this,arguments)||this}v(a,b);a.setPageName=function(d){a.ta=d};a.prototype.G=function(e){var c=b.prototype.G.call(this,e),k=h.yc.build(e);k.PLT=e.timestamp()-e.startTime;k.VCT=e.vct;k.PLC=1;c.metrics=k;c.timestamp=e.timestamp();k=(new h.ResourceTimingInfoBuilder(e.resTiming(),null,e.startTime)).build();null!==k&&(c.resourceTimingInfo=k);d.utils.isDefined(e.userPageName)&&(c.userPageName=e.userPageName);!d.utils.isDefined(c.userPageName)&&d.utils.isDefined(a.ta)&&
(h.fa.Hd("userPageName",a.ta,d.conf.ab)?c.userPageName=a.ta:h.fa.Ra("userPageName",d.conf.ab),a.ta=void 0);return c};return a}(h.Xa);h.Cb=a})(d.events||(d.events={}))})(k||(k={}));(function(d){(function(d){var a=function(d){function h(){return null!==d&&d.apply(this,arguments)||this}v(h,d);h.prototype.G=function(e){var h=d.prototype.G.call(this,e);h&&(h.metrics.VDC=e.digestCount()||0);return h};return h}(d.ye);d.ui=a})(d.events||(d.events={}))})(k||(k={}));(function(d){var h=d.events||(d.events={});
h.xg={};d=[{Ka:h.PageView,Fa:new h.oa},{Ka:h.Ajax,Fa:new h.ze},{Ka:h.AdrumAjax,Fa:new h.qh},{Ka:h.Error,Fa:new h.xi},{Ka:h.VPageView,Fa:new h.ye},{Ka:h.AnySpaVPageView,Fa:new h.Cb},{Ka:d.ng.NgVPageView,Fa:new h.ui}];for(var a=0;a<d.length;a++){var b=d[a];b.Ka.prototype._regId=a;h.xg[a]=b.Fa}})(k||(k={}));(function(d){(function(h){h.reportEvent=function(h){var b=d.events.xg[h._regId];b?(b=b.G(h),d.utils.isDefined(b)&&(d.log("M292",d.EventType[h.type()]),d.channel.report(b))):d.log("M291",d.EventType[h.type()])}})(d.reporter||
(d.reporter={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(){this.ready=!1}b.prototype.onReady=function(){this.ready=!0;this.channel.onResolverReady()};b.prototype.isReady=function(){this.ready||d.log("M293");return this.ready};b.prototype.init=function(d){this.channel=d};return b}();h.Li=a})(d.commands||(d.commands={}))})(k||(k={}));(function(d){(function(h){var a=new h.Li;d.channel.addResolver(a);h.marks={};h.mark=function(b,a){d.log("M294",b,a);h.marks[b]=a};h.reportOnload=
function(b){d.utils.oSTO(function(){d.log("M295");d.reporter.reportEvent(b);a.onReady()},d.conf.Ji)};h.reportEvent=function(){d.reporter.reportEvent.apply(d.reporter,arguments)};h.addResolver=function(b){d.channel.addResolver(b)};h.reportXhr=function(b){d.log("M296");d.Hb.qg()==d.Hb.Od?(d.log("M297"),d.utils.oSTO(function(){b.parentPhaseId(d.Hb.pg(b));d.reporter.reportEvent(b)},0)):(b.parentPhaseId(d.Hb.pg(b)),d.reporter.reportEvent(b))};h.listenForOkToSendChildFrameBeacons=function(b){d.log("M298");
try{b()}catch(h){d.exception(h,"M299")}};h.reportPageError=function(b){var h=b.url();d.log("M300",b.msg(),h,b.line(),b.stack());h&&0!==h.length||b.url("CROSSORIGIN");d.reporter.reportEvent(b)};h.setPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.events.oa.setPageName(b)};h.setVirtualPageName=function(b){d.utils.isString(b)&&0<d.utils.trim(b).length&&d.conf.spa2&&d.events.Cb.setPageName(b)};h.addUserData=function(b,h){d.events.oa.addUserData(b,h)};h.call=function(d){d()}})(d.commands||
(d.commands={}))})(k||(k={}));(function(d){(function(d){d.df=function(a){return encodeURIComponent(d.Z.Dl(a))}})(d.utils||(d.utils={}))})(k||(k={}));(function(d){(function(h){var a=function(){function b(){}b.prototype.setUp=function(){this.ul();d.utils.addEventListener(window,"pagehide",b.Ud);d.utils.addEventListener(window,"beforeunload",b.Ud);d.utils.addEventListener(window,"unload",b.Ud)};b.prototype.ul=function(){(this.startTime=b.Nj()||b.Mj())&&d.commands.mark("starttime",this.startTime)};b.Nj=
function(){var b;try{if(d.utils.isDefined(window.external)&&d.utils.isNumber(window.external.pageT))b=(new Date).getTime()-window.external.pageT;else if(d.utils.isDefined(window.gtbExternal)&&d.utils.isFunction(window.gtbExternal.pageT)){var e=window.gtbExternal.pageT();d.utils.isNumber(e)&&(b=(new Date).getTime()-e)}else d.utils.isDefined(window.chrome)&&d.utils.isFunction(window.chrome.csi)&&(e=window.chrome.csi(),d.utils.isDefined(e)&&d.utils.isNumber(e.pageT)&&(b=(new Date).getTime()-e.pageT));
b&&(b=Math.round(b),d.log("M301",b))}catch(h){d.exception(h,"M302")}return b};b.Mj=function(){var b=d.correlation.startTimeCookie;if(b){d.log("M303",b.startTime,b.startPage);var e=d.utils.df(document.referrer);if(e===b.startPage)if(isNaN(b.startTime))d.log("M304",b.startTime);else return b.startTime;else d.log("M305",e,b.startPage)}else d.log("M306")};b.Aj=function(b,e){var h=document.domain,a="https:"===document.location.protocol,k="ADRUM=s="+Number(new Date)+"&r="+d.utils.df(document.location.href),
n=k+";path=/";a&&(n+=";secure");d.log("M307",k);if(!d.conf.useStrictDomainCookies){for(var a=b(),h=h.split("."),m="",p=h.length-1;0<=p;p--){m="."+h[p]+m;d.log("M308",m);e(n+";domain="+m);var r=b();if(r!=a&&0<=r.indexOf(k)){d.log("M309");d.log("M310");return}}d.log("M311")}d.log("M312");e(n);d.log("M313")};return b}();a.Ud=function(){var d=!1;return function(){d||(d=!0,a.Aj(function(){return document.cookie},function(d){document.cookie=d}))}}();h.pn=a;h.zm=new a})(d.monitor||(d.monitor={}))})(k||(k=
{}));(function(d){d.log("M314");d.monitor.zm.setUp();d.q.processQ();d.initEXTDone=!0;d.log("M315")})(k||(k={}))}};})();
